name: mtrack
channels:
  - nvidia/label/cuda-11.8.0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cuda-nvcc=11.8.89
  - cudatoolkit=11.8.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.14
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - attributee==0.1.9
      - bypy==1.8.9
      - causal-conv1d==1.4.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - dill==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - filelock==3.13.1
      - fsspec==2024.2.0
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.25.1
      - idna==3.4
      - jinja2==3.1.3
      - jpeg4py==0.1.4
      - jsonpatch==1.33
      - lmdb==1.7.5
      - loguru==0.7.3
      - mamba-ssm==2.2.2
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.3
      - opencv-python==4.12.0.88
      - packaging==24.1
      - pandas==2.3.3
      - pillow==10.2.0
      - pycocotools==2.0.11
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.28.1
      - requests-toolbelt==1.0.0
      - safetensors==0.4.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - thop==0.1.1-2209072238
      - tikzplotlib==0.10.1
      - timm==0.5.4
      - tokenizers==0.19.1
      - torch==2.1.1+cu118
      - torchaudio==2.1.1+cu118
      - torchvision==0.16.1+cu118
      - tqdm==4.66.5
      - transformers==4.42.3
      - triton==2.1.0
      - typing-extensions==4.9.0
      - urllib3==1.26.13
      - visdom==0.2.4
      - wandb==0.23.1
      - yacs==0.1.8
prefix: /root/miniconda3/envs/mtrack
